# generated by make-surrogate-list.rb
# generated at Tue Apr 14 07:24:37 +0900 2009
$surrogates = { '129.97.134.71' => '333', '206.167.141.10' => '9999', '24.215.0.24' => '9999', '70.38.0.135' => '9999',}
