# generated by make-surrogate-list.rb
# generated at Tue Apr 14 07:24:37 +0900 2009
$surrogates = { '193.136.216.20' => '9999', '81.92.192.129' => '9999', '193.136.28.167' => '9999', '194.117.2.41' => '9999',}
