# generated by make-surrogate-list.rb
# generated at Tue Apr 14 07:24:37 +0900 2009
$surrogates = { '130.235.34.30' => '100', '130.239.18.137' => '9999', '82.96.2.196' => '9999', '193.10.239.170' => '9999',}
